//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GM4ManagerWPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GM4ManagerWPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Folder.
        /// </summary>
        internal static string btnAddFolder {
            get {
                return ResourceManager.GetString("btnAddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Member.
        /// </summary>
        internal static string btnAddMember {
            get {
                return ResourceManager.GetString("btnAddMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Folder.
        /// </summary>
        internal static string btnCreateFolder {
            get {
                return ResourceManager.GetString("btnCreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Network Share.
        /// </summary>
        internal static string btnLoadNetworkShare {
            get {
                return ResourceManager.GetString("btnLoadNetworkShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Member.
        /// </summary>
        internal static string btnRemoveMember {
            get {
                return ResourceManager.GetString("btnRemoveMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        internal static string btnScan {
            get {
                return ResourceManager.GetString("btnScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string btnSelect {
            get {
                return ResourceManager.GetString("btnSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to as Admin.
        /// </summary>
        internal static string cbAsAdmin {
            get {
                return ResourceManager.GetString("cbAsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show only Folders where I have Permissions.
        /// </summary>
        internal static string cbOnlyPermissions {
            get {
                return ResourceManager.GetString("cbOnlyPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string colDescription {
            get {
                return ResourceManager.GetString("colDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Permission.
        /// </summary>
        internal static string colEditRights {
            get {
                return ResourceManager.GetString("colEditRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name.
        /// </summary>
        internal static string colGroupName {
            get {
                return ResourceManager.GetString("colGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member.
        /// </summary>
        internal static string colMember {
            get {
                return ResourceManager.GetString("colMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read / Write.
        /// </summary>
        internal static string colModify {
            get {
                return ResourceManager.GetString("colModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        internal static string colPermissions {
            get {
                return ResourceManager.GetString("colPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Only.
        /// </summary>
        internal static string colReadAndExecute {
            get {
                return ResourceManager.GetString("colReadAndExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove User.
        /// </summary>
        internal static string colRemoveUser {
            get {
                return ResourceManager.GetString("colRemoveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string colType {
            get {
                return ResourceManager.GetString("colType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string colUser {
            get {
                return ResourceManager.GetString("colUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new Folder.
        /// </summary>
        internal static string headerCreateFolder {
            get {
                return ResourceManager.GetString("headerCreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory Permissions.
        /// </summary>
        internal static string headerDirectoryPermissions {
            get {
                return ResourceManager.GetString("headerDirectoryPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory Structure.
        /// </summary>
        internal static string headerDirectoryStructure {
            get {
                return ResourceManager.GetString("headerDirectoryStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager: {manager}.
        /// </summary>
        internal static string headerManager {
            get {
                return ResourceManager.GetString("headerManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members of the group.
        /// </summary>
        internal static string headerMembers {
            get {
                return ResourceManager.GetString("headerMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants the added user permission to manage group members..
        /// </summary>
        internal static string helpForAsAdmin {
            get {
                return ResourceManager.GetString("helpForAsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Manager.
        /// </summary>
        internal static string lblCurrentManager {
            get {
                return ResourceManager.GetString("lblCurrentManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current User.
        /// </summary>
        internal static string lblCurrentUser {
            get {
                return ResourceManager.GetString("lblCurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string lblLanguage {
            get {
                return ResourceManager.GetString("lblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        internal static string lblManager {
            get {
                return ResourceManager.GetString("lblManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Share.
        /// </summary>
        internal static string lblNetworkShare {
            get {
                return ResourceManager.GetString("lblNetworkShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search term.
        /// </summary>
        internal static string lblSearchterm {
            get {
                return ResourceManager.GetString("lblSearchterm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Group {name}.
        /// </summary>
        internal static string loadGroup {
            get {
                return ResourceManager.GetString("loadGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Permissions....
        /// </summary>
        internal static string loadingPermissions {
            get {
                return ResourceManager.GetString("loadingPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string menuDark {
            get {
                return ResourceManager.GetString("menuDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string menuEnglish {
            get {
                return ResourceManager.GetString("menuEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        internal static string menuGerman {
            get {
                return ResourceManager.GetString("menuGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show Group Members.
        /// </summary>
        internal static string menuGroupMembers {
            get {
                return ResourceManager.GetString("menuGroupMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        internal static string menuLanguages {
            get {
                return ResourceManager.GetString("menuLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string menuLight {
            get {
                return ResourceManager.GetString("menuLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string menuTheme {
            get {
                return ResourceManager.GetString("menuTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Permission, ask your Administrator.
        /// </summary>
        internal static string msgAskYourAdministrator {
            get {
                return ResourceManager.GetString("msgAskYourAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding user or setting permission:\n{message}.
        /// </summary>
        internal static string msgErrorAddingUser {
            get {
                return ResourceManager.GetString("msgErrorAddingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find Member.
        /// </summary>
        internal static string msgErrorCouldNotFindMember {
            get {
                return ResourceManager.GetString("msgErrorCouldNotFindMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is already in the group.
        /// </summary>
        internal static string msgErrorUserAlreadyInGroup {
            get {
                return ResourceManager.GetString("msgErrorUserAlreadyInGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load permissions:{message}..
        /// </summary>
        internal static string msgFailedToLoadPermissions {
            get {
                return ResourceManager.GetString("msgFailedToLoadPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder already exists!.
        /// </summary>
        internal static string msgFolderAlreadyExists {
            get {
                return ResourceManager.GetString("msgFolderAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder &quot;{folder}&quot; created successfully.
        /// </summary>
        internal static string msgFolderCreatedSuccessfully {
            get {
                return ResourceManager.GetString("msgFolderCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string msgHeaderError {
            get {
                return ResourceManager.GetString("msgHeaderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string msgHeaderSuccess {
            get {
                return ResourceManager.GetString("msgHeaderSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string msgHeaderWarning {
            get {
                return ResourceManager.GetString("msgHeaderWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Folder selected..
        /// </summary>
        internal static string msgNoFolderSelected {
            get {
                return ResourceManager.GetString("msgNoFolderSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No indirectly managed groups found.
        /// </summary>
        internal static string msgNoIndirectlyManagedGroupsFound {
            get {
                return ResourceManager.GetString("msgNoIndirectlyManagedGroupsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This computer is not part of a domain. Cannot load managed OUs..
        /// </summary>
        internal static string msgNoPartOfADomain {
            get {
                return ResourceManager.GetString("msgNoPartOfADomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No result found for &quot;{domain}&quot; and &quot;{username}&quot;.
        /// </summary>
        internal static string msgNoResultsForDomain {
            get {
                return ResourceManager.GetString("msgNoResultsForDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a folder.
        /// </summary>
        internal static string msgSelectFolderFirst {
            get {
                return ResourceManager.GetString("msgSelectFolderFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a group first.
        /// </summary>
        internal static string msgSelectGroupFirst {
            get {
                return ResourceManager.GetString("msgSelectGroupFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Group first.
        /// </summary>
        internal static string msgSelectPermissionFirst {
            get {
                return ResourceManager.GetString("msgSelectPermissionFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {username} was added and granted &apos;Write Members&apos; permission.
        /// </summary>
        internal static string msgUserAddedSucessfully {
            get {
                return ResourceManager.GetString("msgUserAddedSucessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {username} was added.\n&apos;Write Members&apos; permission already exists.
        /// </summary>
        internal static string msgUserAddedSucessfullyPermissionAlready {
            get {
                return ResourceManager.GetString("msgUserAddedSucessfullyPermissionAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User DN could not be found..
        /// </summary>
        internal static string msgUserCoulNotBeFound {
            get {
                return ResourceManager.GetString("msgUserCoulNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove user.\n{message}.
        /// </summary>
        internal static string msgUserRemoveFailed {
            get {
                return ResourceManager.GetString("msgUserRemoveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User was successfully removed:\n{member}.
        /// </summary>
        internal static string msgUserSucessfullyRemoved {
            get {
                return ResourceManager.GetString("msgUserSucessfullyRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting....
        /// </summary>
        internal static string startingText {
            get {
                return ResourceManager.GetString("startingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer.
        /// </summary>
        internal static string tabExplorer {
            get {
                return ResourceManager.GetString("tabExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        internal static string tabManager {
            get {
                return ResourceManager.GetString("tabManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inheritance is disabled, Permissions are unique for this folder.
        /// </summary>
        internal static string tooltipInheritanceDisabled {
            get {
                return ResourceManager.GetString("tooltipInheritanceDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled inheritance, Permissions are the same as the parent directory.
        /// </summary>
        internal static string tooltipInheritanceEnabled {
            get {
                return ResourceManager.GetString("tooltipInheritanceEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user / Group can only read the content of this Folder..
        /// </summary>
        internal static string ttReadOnly {
            get {
                return ResourceManager.GetString("ttReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The User / the Group can change the content of this Folder..
        /// </summary>
        internal static string ttReadWrite {
            get {
                return ResourceManager.GetString("ttReadWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string txtDescription {
            get {
                return ResourceManager.GetString("txtDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Inheritance and copy permissions.
        /// </summary>
        internal static string txtDisableInheritance {
            get {
                return ResourceManager.GetString("txtDisableInheritance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string txtError {
            get {
                return ResourceManager.GetString("txtError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: No Members Found.
        /// </summary>
        internal static string txtErrorNoMembersFound {
            get {
                return ResourceManager.GetString("txtErrorNoMembersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on load.
        /// </summary>
        internal static string txtErrorOnLoad {
            get {
                return ResourceManager.GetString("txtErrorOnLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name.
        /// </summary>
        internal static string txtGroupName {
            get {
                return ResourceManager.GetString("txtGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inheritance Deactivated.
        /// </summary>
        internal static string txtInheritanceDeactivated {
            get {
                return ResourceManager.GetString("txtInheritanceDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string txtLoading {
            get {
                return ResourceManager.GetString("txtLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member.
        /// </summary>
        internal static string txtMember {
            get {
                return ResourceManager.GetString("txtMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Folder Name.
        /// </summary>
        internal static string txtNewFolderName {
            get {
                return ResourceManager.GetString("txtNewFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Computer does not have a connection to a Domain.
        /// </summary>
        internal static string txtNoConnectionToDomain {
            get {
                return ResourceManager.GetString("txtNoConnectionToDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path not found.
        /// </summary>
        internal static string txtPathNotFound {
            get {
                return ResourceManager.GetString("txtPathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a network directory....
        /// </summary>
        internal static string txtPleaseSelectNetworkDirectory {
            get {
                return ResourceManager.GetString("txtPleaseSelectNetworkDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Manager For Manager.
        /// </summary>
        internal static string txtProgramName {
            get {
                return ResourceManager.GetString("txtProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove User.
        /// </summary>
        internal static string txtRemoveUser {
            get {
                return ResourceManager.GetString("txtRemoveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Active Directory.
        /// </summary>
        internal static string windowtitleAdSearch {
            get {
                return ResourceManager.GetString("windowtitleAdSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Members.
        /// </summary>
        internal static string windowTitleShowGroupMembers {
            get {
                return ResourceManager.GetString("windowTitleShowGroupMembers", resourceCulture);
            }
        }
    }
}
