//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GM4ManagerWPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GM4ManagerWPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Member.
        /// </summary>
        internal static string btnAddMember {
            get {
                return ResourceManager.GetString("btnAddMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Network Share.
        /// </summary>
        internal static string btnLoadNetworkShare {
            get {
                return ResourceManager.GetString("btnLoadNetworkShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove Member.
        /// </summary>
        internal static string btnRemoveMember {
            get {
                return ResourceManager.GetString("btnRemoveMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        internal static string btnScan {
            get {
                return ResourceManager.GetString("btnScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string btnSelect {
            get {
                return ResourceManager.GetString("btnSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to as Admin.
        /// </summary>
        internal static string cbAsAdmin {
            get {
                return ResourceManager.GetString("cbAsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show only Folders where I have Permissions.
        /// </summary>
        internal static string cbOnlyPermissions {
            get {
                return ResourceManager.GetString("cbOnlyPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string colDescription {
            get {
                return ResourceManager.GetString("colDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name.
        /// </summary>
        internal static string colGroupName {
            get {
                return ResourceManager.GetString("colGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member.
        /// </summary>
        internal static string colMember {
            get {
                return ResourceManager.GetString("colMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        internal static string colPermissions {
            get {
                return ResourceManager.GetString("colPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string colUser {
            get {
                return ResourceManager.GetString("colUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members of the group.
        /// </summary>
        internal static string headerMembers {
            get {
                return ResourceManager.GetString("headerMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Manager.
        /// </summary>
        internal static string lblCurrentManager {
            get {
                return ResourceManager.GetString("lblCurrentManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current User.
        /// </summary>
        internal static string lblCurrentUser {
            get {
                return ResourceManager.GetString("lblCurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string lblLanguage {
            get {
                return ResourceManager.GetString("lblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        internal static string lblManager {
            get {
                return ResourceManager.GetString("lblManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Share.
        /// </summary>
        internal static string lblNetworkShare {
            get {
                return ResourceManager.GetString("lblNetworkShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search term.
        /// </summary>
        internal static string lblSearchterm {
            get {
                return ResourceManager.GetString("lblSearchterm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string menuEnglish {
            get {
                return ResourceManager.GetString("menuEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        internal static string menuGerman {
            get {
                return ResourceManager.GetString("menuGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        internal static string menuLanguages {
            get {
                return ResourceManager.GetString("menuLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Permission, ask your Administrator.
        /// </summary>
        internal static string msgAskYourAdministrator {
            get {
                return ResourceManager.GetString("msgAskYourAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding user or setting permission:\n{message}.
        /// </summary>
        internal static string msgErrorAddingUser {
            get {
                return ResourceManager.GetString("msgErrorAddingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find Member.
        /// </summary>
        internal static string msgErrorCouldNotFindMember {
            get {
                return ResourceManager.GetString("msgErrorCouldNotFindMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is already in the group.
        /// </summary>
        internal static string msgErrorUserAlreadyInGroup {
            get {
                return ResourceManager.GetString("msgErrorUserAlreadyInGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string msgHeaderError {
            get {
                return ResourceManager.GetString("msgHeaderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string msgHeaderSuccess {
            get {
                return ResourceManager.GetString("msgHeaderSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This computer is not part of a domain. Cannot load managed OUs..
        /// </summary>
        internal static string msgNoPartOfADomain {
            get {
                return ResourceManager.GetString("msgNoPartOfADomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No result found for &quot;{domain}&quot; and &quot;{username}&quot;.
        /// </summary>
        internal static string msgNoResultsForDomain {
            get {
                return ResourceManager.GetString("msgNoResultsForDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a group first.
        /// </summary>
        internal static string msgSelectGroupFirst {
            get {
                return ResourceManager.GetString("msgSelectGroupFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {username} was added and granted &apos;Write Members&apos; permission.
        /// </summary>
        internal static string msgUserAddedSucessfully {
            get {
                return ResourceManager.GetString("msgUserAddedSucessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {username} was added.\n&apos;Write Members&apos; permission already exists.
        /// </summary>
        internal static string msgUserAddedSucessfullyPermissionAlready {
            get {
                return ResourceManager.GetString("msgUserAddedSucessfullyPermissionAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User DN could not be found..
        /// </summary>
        internal static string msgUserCoulNotBeFound {
            get {
                return ResourceManager.GetString("msgUserCoulNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove user.\n{message}.
        /// </summary>
        internal static string msgUserRemoveFailed {
            get {
                return ResourceManager.GetString("msgUserRemoveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User was successfully removed:\n{member}.
        /// </summary>
        internal static string msgUserSucessfullyRemoved {
            get {
                return ResourceManager.GetString("msgUserSucessfullyRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        internal static string tabManager {
            get {
                return ResourceManager.GetString("tabManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string txtDescription {
            get {
                return ResourceManager.GetString("txtDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string txtError {
            get {
                return ResourceManager.GetString("txtError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: No Members Found.
        /// </summary>
        internal static string txtErrorNoMembersFound {
            get {
                return ResourceManager.GetString("txtErrorNoMembersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on load.
        /// </summary>
        internal static string txtErrorOnLoad {
            get {
                return ResourceManager.GetString("txtErrorOnLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name.
        /// </summary>
        internal static string txtGroupName {
            get {
                return ResourceManager.GetString("txtGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member.
        /// </summary>
        internal static string txtMember {
            get {
                return ResourceManager.GetString("txtMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Computer does not have a connection to a Domain.
        /// </summary>
        internal static string txtNoConnectionToDomain {
            get {
                return ResourceManager.GetString("txtNoConnectionToDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path not found.
        /// </summary>
        internal static string txtPathNotFound {
            get {
                return ResourceManager.GetString("txtPathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a network directory.
        /// </summary>
        internal static string txtPlaseSelectNetworkDirectory {
            get {
                return ResourceManager.GetString("txtPlaseSelectNetworkDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Manager For Manager.
        /// </summary>
        internal static string txtProgramName {
            get {
                return ResourceManager.GetString("txtProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove User.
        /// </summary>
        internal static string txtRemoveUser {
            get {
                return ResourceManager.GetString("txtRemoveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AD Search.
        /// </summary>
        internal static string windowtitleAdSearch {
            get {
                return ResourceManager.GetString("windowtitleAdSearch", resourceCulture);
            }
        }
    }
}
